apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security-system

resources:
  - https://github.com/bitnami-labs/sealed-secrets/raw/refs/tags/v0.34.0/helm/sealed-secrets/crds/bitnami.com_sealedsecrets.yaml

helmCharts:
  - name: sealed-secrets
    repo: https://bitnami-labs.github.io/sealed-secrets
    releaseName: sealed-secrets
    version: 2.18.0
    valuesFile: sealed-secrets.values.yaml
