apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: localpv-hot
  annotations:
    cas.openebs.io/config: |
      - name: StorageType
        value: "hostpath"
      - name: BasePath
        value: "/var/localpv/hot"
    openebs.io/cas-type: local
provisioner: openebs.io/local
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
  - matchLabelExpressions:
      - key: storage-tier/hot
        values: ['true']
