apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - ../base
  - config-map.yaml

patches:
  - target:
      kind: DaemonSet
      name: kube-flannel
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --iface=tailscale0
