apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
helmCharts:
  - name: metrics-server
    repo: https://kubernetes-sigs.github.io/metrics-server
    releaseName: metrics-server
    version: 3.13.0
    valuesFile: metrics-server.values.yaml
