apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability-system
helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: kube-prometheus-stack
    version: 56.6.0
    includeCRDs: true
    valuesFile: values.yaml
