apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability-system
helmCharts:
  - name: tempo
    repo: https://grafana.github.io/helm-charts
    releaseName: tempo
    version: 1.7.1
    valuesFile: values.yaml
