##
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
spec:
  description: Initializer project (Disabled for security reasons).
  sourceRepos: []
  sourceNamespaces: []
  destinations: []
  namespaceResourceBlacklist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
