apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability-system
helmCharts:
  - name: promtail
    repo: https://grafana.github.io/helm-charts
    releaseName: promtail
    version: 6.15.5
    valuesFile: values.yaml
