apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-router
  labels:
    app: kube-router
spec:
  selector:
    matchLabels:
      app: kube-router
  template:
    metadata:
      labels:
        app: kube-router
    spec:
      serviceAccountName: kube-router
      hostNetwork: true
      tolerations:
        - operator: Exists
      containers:
        - name: kube-router
          image: cloudnativelabs/kube-router:latest
          args:
            - --run-router=true
            - --run-service-proxy=true
            - --run-firewall=false
            - --overlay=vxlan
            - --mtu=1450
          securityContext:
            privileged: true
          resources:
            limits:
              cpu: '1000m'
              memory: '512Mi'
            requests:
              cpu: '100m'
              memory: '64Mi'
