apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability-system
helmCharts:
  - name: loki
    repo: https://grafana.github.io/helm-charts
    releaseName: loki
    version: 5.43.3
    valuesFile: values.yaml
