apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-dex-secret
  namespace: gitops-system
spec:
  encryptedData:
    github.clientSecret: AgApC5H9LWHCKITdOng4h+/Js7FQ+d5OLuiNMd7RpYgemeOch7+5b/RaFkVxMwvBk4kQ3Z0DbB8nCSAXBm/xD61nYguxexdvRzrb6z+1AGT0rEXLFFUxLEDdZg7zZDEAMcxgGBErDPUJYjpq+33yCeumdnMBdEGoan2TFOtqTnghtCzA4QiT12hatxwTRu9xZBFwFFcC+lr6HyuwlNyb7TAA3aCt5GNdStrdwYyFnidLz5wLjhOAqAKrol7IgmP1TFNHB4S1YuDG/4ffRgZdJG9uSKbtDSmab2w3nSR3FNv818PXwq6QFzERHoxocu1N2WwW/PcU5fsga7MiwvdvODAHIGctP/6Z8/vHBaJBa5wv9x5J9LLd3hlFLI4gnxXebN6/jliLDgii55Cgs8r1NXmt9AyLYuYr8onJpTvyXuA7jzLUypalMidC5sDQGrZSY1h8BWynLF7zqDrlG+MNtEWSFx+ZBWDWUX5qH1AOpm5YKQkJCP6Tq1qNxjA89EqK0x9ndJA3K++PyzaA/FLM6JVy7GYR+CnFWpKP0SA3p3ANS+2oaJzl6Jz1M3vAXfpjdjh56+9h4+iYhw6VHGCR5zBE8kiO7aeitLBxkMIP5KpxdN4Q/betp1dAz7eVeTJI6UCB684yN02aAuqU0X6FirL+0dTVWx8t3fpcYuVhzh5tdi7MqZSQwqpX2urolfWzyv2WJqn6tcMbNfMVgRFb5/FZPeEYQjVxtKQMHOqeZw1GAdO+ukMVZQ2+Qg==
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-dex-secret
        app.kubernetes.io/part-of: argocd
      name: argocd-dex-secret
      namespace: gitops-system
    type: Opaque
