apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
helmCharts:
  - name: coredns
    repo: https://coredns.github.io/helm
    releaseName: coredns
    version: 1.45.0
    valuesFile: coredns.values.yaml

  - name: node-local-dns
    repo: https://charts.deliveryhero.io
    releaseName: dns-cache
    version: 2.1.0
    valuesFile: dns-cache.values.yaml
